app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	if(!Config::get('92five.install'))
	{
		return Redirect::to('install');
	}
	if(!Sentry::check())
	{
		return View::make('login.index');
	}
	else
	{
		return Redirect::to('dashboard');
	}	
});

Route::get('/forgotpassword', function()
{
	return View::make('login.forgotpassword');
});
Route::get('/login', function()
{
	if(!Sentry::check())
	{
		return View::make('login.index');
	}
	else
	{
		return Redirect::to('dashboard');
	}
});
Route::get('/logout', function(){

	Sentry::logout();
	return Redirect::to('/login');
});
Route::group(array('prefix'=>'install','before'=>'install'),function() 
{
    Route::get('/','InstallController@getIndex');
    Route::get('/database','InstallController@getDatabase');
    Route::post('/database','InstallController@postDatabase');
    Route::post('/timezone','InstallController@postTimeZone');
    Route::post('/adminaccount','InstallController@postAdminAccount');
});
Route::post('/auth/login', 'AuthController@authLogin');
Route::post('/auth/forgotpassword', 'AuthController@authForgotPassword');
Route::get('/auth/recoverpassword', 'AuthController@authRecoverPassword');
Route::post('/auth/updatepassword', 'AuthController@authUpdatePassword');
Route::get('/auth/activateuser', 'AuthController@authActivateUser');
Route::post('/auth/createuser', 'AuthController@authCreateUser');
Route::get('/auth/verifyemail','AuthController@authVerifyEmail');
Route::group(array('prefix'=>'dashboard','before'=>'auth'),function() 
{

				 Route::get('/', 'Controllers\Domain\Dashboard\DashboardController@getIndex');
				 if(Request::ajax())
				 {
				 	Route::get('/todos','Controllers\Domain\Dashboard\DashboardController@getToDos');
				 	Route::put('/todos/{id?}', 'Controllers\Domain\Dashboard\DashboardController@putToDos');
				 	Route::get('/quicknote','Controllers\Domain\Dashboard\DashboardController@getQuickNote');
				 	Route::put('/quicknote','Controllers\Domain\Dashboard\DashboardController@putQuickNote');
				 	Route::get('/users','Controllers\Domain\Dashboard\DashboardController@getUsersList');
				 	Route::get('/projects/edit/deletefile/{id}','Controllers\Domain\Dashboard\DashboardController@getDeleteFile');
				 	Route::put('/task/update/{id?}', 'Controllers\Domain\Dashboard\TaskController@updateStatus');
				 	Route::get('/users/project/{id?}','Controllers\Domain\Dashboard\DashboardController@getProjectUsersList');
				 	Route::post('/tasks/add', 'Controllers\Domain\Dashboard\TaskController@postAddTask');
				 	Route::post('/tasks/subtask', 'Controllers\Domain\Dashboard\TaskController@postAddSubTask');
				 	Route::delete('/tasks/subtask/{id?}', 'Controllers\Domain\Dashboard\TaskController@deleteSubTask');
				 	Route::post('/tasks/edit/subtask', 'Controllers\Domain\Dashboard\TaskController@postAddSubTask');
				 	Route::delete('/tasks/edit/subtask/{id?}', 'Controllers\Domain\Dashboard\TaskController@deleteSubTask');
				 	Route::post('/tasks/edit/update', 'Controllers\Domain\Dashboard\TaskController@postEditTask');
				 	Route::get('/tasks/edit/add/files/deletefile/{id}','Controllers\Domain\Dashboard\DashboardController@getDeleteFile');
				 	Route::get('/calendar/events/{id?}','Controllers\Domain\Dashboard\CalendarController@getEvents');
				 	/***TimeSheet***/
				 	Route::get('timesheet/entry/{day?}', 'Controllers\Domain\Dashboard\TimesheetController@getEntries');
				 	Route::get('todo','Controllers\Domain\Dashboard\TodoController@getTodos');
				 	Route::put('/todo/{id?}', 'Controllers\Domain\Dashboard\TodoController@putTodos');
				 	Route::post('todo','Controllers\Domain\Dashboard\TodoController@postTodos');
				 	Route::delete('todo/{id?}','Controllers\Domain\Dashboard\TodoController@deleteTodos');

				}
				Route::get('roles',function(){
					return View::make('dashboard.roles');
				});
				Route::get('projects','Controllers\Domain\Dashboard\ProjectController@getIndex');
				Route::get('Projects','Controllers\Domain\Dashboard\ProjectController@getIndex');
				Route::get('projects/{id}','Controllers\Domain\Dashboard\ProjectController@getViewProject')->where('id', '[0-9]+');
				Route::get('/download/{md5}','Controllers\Domain\Dashboard\DashboardController@getDownloadFile');
				Route::post('projects/delete','Controllers\Domain\Dashboard\ProjectController@deleteProject');
				
				Route::get('projects/edit/{id}','Controllers\Domain\Dashboard\ProjectController@getEditProject')->where('id', '[0-9]+');
				Route::post('projects/edit/{id}','Controllers\Domain\Dashboard\ProjectController@postEditProject');
				Route::post('projects/edit/add/files','Controllers\Domain\Dashboard\ProjectController@postAddFiles');
				Route::get('projects/add','Controllers\Domain\Dashboard\ProjectController@getAddProject');
				Route::post('projects/add','Controllers\Domain\Dashboard\ProjectController@postCreateProject');
				Route::post('projects/add/files','Controllers\Domain\Dashboard\ProjectController@postAddFiles');
				Route::get('projects/add/done',function(){
					return Redirect::to('dashboard/projects')->with('status','success')->with('message','Project Added');
				});
				Route::get('projects/edit/done/{id?}',function($id){
					return Redirect::to('dashboard/projects/'.$id)->with('status','success')->with('message','Project Updated');
				});
				/************** Tasks **************/
				Route::get('tasks','Controllers\Domain\Dashboard\TaskController@getIndex');
				Route::get('Tasks','Controllers\Domain\Dashboard\TaskController@getIndex');
				Route::get('/tasks/project/{id?}', 'Controllers\Domain\Dashboard\TaskController@getProjectsTasks');
				Route::get('/tasks/add','Controllers\Domain\Dashboard\TaskController@getAddTasks');
				Route::get('/tasks/add/files/{id?}','Controllers\Domain\Dashboard\TaskController@getAddFiles');
				Route::post('/tasks/add/files/{id?}','Controllers\Domain\Dashboard\TaskController@postAddFiles');
				Route::get('/tasks/{id?}','Controllers\Domain\Dashboard\TaskController@getViewTask');
				Route::get('/tasks/edit/{id?}','Controllers\Domain\Dashboard\TaskController@getEditTask');
				Route::get('/tasks/edit/add/files/{id?}','Controllers\Domain\Dashboard\TaskController@getEditFiles');
				Route::post('/tasks/edit/add/files/{id?}','Controllers\Domain\Dashboard\TaskController@postAddFiles');
				Route::post('/tasks/delete','Controllers\Domain\Dashboard\TaskController@getDeleteIt');
				Route::get('/task/added',function(){
						return Redirect::to('dashboard/tasks')->with('status','success')->with('message','Task Added');
				});
				Route::get('/task/edited/{id?}',function($id){
						return Redirect::to('dashboard/tasks/'.$id)->with('status','success')->with('message','Task Updated');
				});
				Route::put('task/subtasks/{id?}','Controllers\Domain\Dashboard\TaskController@updateSubTask');
				/************* Routes for Calendar **************/
				Route::get('calendar','Controllers\Domain\Dashboard\CalendarController@getIndex');
				Route::post('calendar/add','Controllers\Domain\Dashboard\CalendarController@addEvent');
				Route::post('calendar/event/delete','Controllers\Domain\Dashboard\CalendarController@deleteEvent');
				Route::get('calendar/event/edit/{id?}','Controllers\Domain\Dashboard\CalendarController@getEditEvent');
				Route::post('calendar/event/edit/{id?}','Controllers\Domain\Dashboard\CalendarController@postEditEvent');
				Route::get('calendar/event/createdbyme','Controllers\Domain\Dashboard\CalendarController@getEventsCreatedByMe');

				/************* Routes for Timesheet **************/
				Route::get('timesheet','Controllers\Domain\Dashboard\TimesheetController@getIndex');
				Route::post('timesheet/entry/add','Controllers\Domain\Dashboard\TimesheetController@addEntry');
				Route::post('timesheet/entry/delete','Controllers\Domain\Dashboard\TimesheetController@deleteEntry');
				Route::post('timesheet/entry','Controllers\Domain\Dashboard\TimesheetController@getDateEntries');
				Route::get('timesheet/entry/edit/{id?}','Controllers\Domain\Dashboard\TimesheetController@getEditEntries');
				Route::post('timesheet/entry/edit/{id?}','Controllers\Domain\Dashboard\TimesheetController@postEditEntry');
				/**************** Routes for Todos *********************/
				Route::get('mytodos','Controllers\Domain\Dashboard\TodoController@getIndex');
				Route::get('mytodos/markallcompleted','Controllers\Domain\Dashboard\TodoController@markAllCompleted');
				Route::get('mytodos/deletecompleted','Controllers\Domain\Dashboard\TodoController@deleteCompleted');
				Route::get('mytodos/deleteall','Controllers\Domain\Dashboard\TodoController@deleteAll');
				/**************** Reports *******************/
				Route::get('reports','Controllers\Domain\Dashboard\ReportController@getIndex');
				Route::post('reports/weekly','Controllers\Domain\Dashboard\ReportController@postWeekly');
				Route::post('reports/weeklytask','Controllers\Domain\Dashboard\ReportController@postWeeklyTask');
				Route::post('reports/weeklyproject','Controllers\Domain\Dashboard\ReportController@postWeeklyProject');
				Route::post('reports/monthly','Controllers\Domain\Dashboard\ReportController@postMonthly');
				Route::post('reports/monthlytask','Controllers\Domain\Dashboard\ReportController@postMonthlyTask');
				Route::post('reports/monthlyproject','Controllers\Domain\Dashboard\ReportController@postMonthlyProject');
				Route::post('reports/projectreport','Controllers\Domain\Dashboard\ReportController@postProjectReport');
				Route::post('reports/usermonthlyproject','Controllers\Domain\Dashboard\ReportController@postUserProjectReport');

app/controllers/domain/dashboard/CalendarController.php
<?php namespace Controllers\Domain\Dashboard;
use Cartalyst\Sentry\Facades\Laravel\Sentry as Sentry;
use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFoundException;

/**
 * Calendar Controller.    
 * @version    1.0.0
 * @author     Chintan Banugaria
 * @copyright  (c) 2014, 92fiveapp
 * @link       http://92fiveapp.com
 **/

class CalendarController extends \BaseController{

	protected $event;

	/**
	* Constructor
	*/
	public function __construct()
	{
		$this->event = \App::make('CalendarInterface');
	}
	/**
	* Get the event dates and events for the currently logged in user
	* @return View
	*/
	public function getIndex()
	{

			//Get the user id of the currently logged in user
			$userId =  \Sentry::getUser()->id;
			//Current Date
			$day = date("Y-m-d");
			//Get events for current date
			$events = $this->event->getEvents($userId,$day);
			//Get all  event dates for the user
			$eventDates = $this->event->getEventDates($userId);
			$todaysDate = new \ExpressiveDate();
		    return \View::make('dashboard.calendar.view')
		   				->with('todaysDate',$todaysDate)
		   				->with('eventDates',$eventDates)
		   				->with('events', $events);
		
	}
	/**
	*	Add Event
	* @return Redirect
	*/
	public function addEvent()
	{
		//Get all the data
		$data = \Input::all();
		//Get the user id of the currently logged in user
		$userId =  \Sentry::getUser()->id;
		//Add event
		$result = $this->event->addEvent($data,$userId);
		return \Redirect::to('dashboard/calendar')->with('status','success')->with('message','Entry Added');
	  
	}
	/**
	* Get Events for a custom day for currently looged in user
	* @return JSON
	*/
	public function getEvents($day)
	{
		//Get the user id of the currently logged in user
		$userId =  \Sentry::getUser()->id;
		//Get the events
		$events =  $this->event->getEvents($userId,$day);
		$jsonEvents = json_encode($events);
		return  $jsonEvents;
		
	}
	/**
	*  Delete Event
	*  @return Redirect 
	*/
	public function deleteEvent()
	{
		$eventId = \Input::get('deleteEventId');
		//Get the user id of the currently logged in user
		$userId =  \Sentry::getUser()->id;
		//Check permission
		$checkpermission = $this->event->checkPermission($eventId,$userId);
		if($checkpermission)
		{
			//Authorized, Delete Event
			$result = $this->event->deleteEvent($eventId,$userId);
			if($result == 'success')
			{
				return \Redirect::to('dashboard/calendar')->with('status','success')->with('message','Entry Deleted');
			}
			else
			{
				//Something went wrong
				return \Redirect::to('dashboard/calendar')->with('status','error')->with('message','Something Went Wrong. Please try again.');
			}
		}
		else
		{
			throw new \NotAuthorizedForEventException();
		}
	}
	/**
	*  View for Edit Event
	*  @return View
	*/
	public function getEditEvent($id)
	{
		try
		{
			$event = \Events::findOrFail($id);
		}
		catch(ModelNotFoundException $e)
		{
			throw new \EventNotFoundException();
		}
		$emaillist = null;
		//Get the user id of the currently logged in user
		$userId =  \Sentry::getUser()->id;
		//Check Permission
		$checkpermission = $this->event->checkPermission($id,$userId);
		if($checkpermission)
		{
			//Authorized, Get Event
			$event = $this->event->getEvent($id);
			foreach ($event['users'] as $user)
		 	{
				if($emaillist == null)
				{
					$emaillist = $user['email'];
				}
				else
				{
					$emaillist = $emaillist.','.$user['email'];
				}
				
			}
			//Wrap Up and generate View	
			return \View::make('dashboard.calendar.edit')
					->with('emaillist',$emaillist)
					->with('event',$event);
		}
		else
		{
			throw new \NotAuthorizedForEventException();
		}
	}
	/**
	* Update Event
	* @return Redirect
	*/
	public function postEditEvent($id)
	{
		//Get all the data
		$data = \Input::all();
		//Get the user id of the currently logged in user
		$userId =  \Sentry::getUser()->id;
		//update Event
		$result = $this->event->editEvent($data,$userId);
		if($result == 'success')
		{
			//Success, Done
			return \Redirect::to('dashboard/calendar')->with('status','success')->with('message','Entry Updated');
		}
		else
		{
			//Error while updating, Notify User
			return \Redirect::to('dashboard/calendar')->with('status','error')->with('message','Something Went Wrong. Please try again.');
		}
	}
	/**
	* Get all events created by a Currently Logged on User
	* @return View
	*/
	public function getEventsCreatedByMe()
	{
		$userId = \Sentry::getUser()->id;
		$events = $this->event->getEventsCreatedByUser($userId);
        return \View::make('dashboard.calendar.createdbyme')
                    ->with('events',$events);
	}
}

app/views/dashboard/calendar/createdbyme.blade.php
@extends('dashboard.default')
@section('head')
<title>92five app - {{trans('92five.eventsCreatedByMe')}}</title>
@stop
@section('content')

<div id="contentwrapper">
  <div class="main_content">
    <div class="row-fluid">
      <div class="span12 project_detail">
        <h2><a href="{{url('/dashboard')}}">{{trans('92five.Dashboard')}}</a> / <a href="{{url('/dashboard/calendar')}}">{{trans('92five.Calendar')}}</a> / {{trans('92five.eventsCreatedByMe')}}</h2>
        @if($events != null)
        <div class="view_proj_sec">
          @foreach($events as $event)
          <div class="view_proj_box">
            <div class="view_proj_inner">
              <div class="view_proj_title">
                <div class="view_proj_btn">
                  <div class="p-icon-inner createventicon"><a class="p-icon-1" title="Edit Event" href="{{url('/dashboard/calendar/event/edit',array($event['id']))}}"><img alt="" src="{{asset('assets/images/dashboard/p-edit.png')}}"></a><a class="p-icon-1 delevent" title="Delete Event" eventid={{$event['id']}} href="#"><img alt="" class="delevent" eventid={{$event['id']}} src="{{asset('assets/images/dashboard/p-delete.png')}}"></a></div>
                </div>
              </div>
              <h3>{{$event['title']}}</h3>
              <span class="eventdate">{{trans('92five.category')}}: {{$event['category']}}</span>
              <div class="projectview_list_sec">
                <div class="projectview_list">
                  <div class="projectview_left">{{trans('92five.date')}}:</div>
                  <div class="projectview_right">
                    <p>{{new ExpressiveDate($event['date'])}}</p>
                  </div>
                </div>
                <div class="projectview_list">
                  <div class="projectview_left">{{trans('92five.from')}}:</div>
                  <div class="projectview_right">
                    <p>{{date('g:iA', strtotime($event['start_time']))}}</p>
                  </div>
                </div>
                <div class="projectview_list">
                  <div class="projectview_left">{{trans('92five.till')}}:</div>
                  <div class="projectview_right">
                    <p>{{date('g:iA', strtotime($event['end_time']))}}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          @endforeach
        </div>
        @else
        <div class="nodatadisplay_main">
          <div class="nodatadisplay">
            <h2> {{trans('92five.noEventFound')}}</h2>
            <div class="nodata_inner">
              <div class="nodata_left"></div>
              <div class="nodata_right"></div>
              <div class="nodata_detail_2"><img src="{{asset('assets/images/dashboard/smile_icon.png')}}" alt=""></div>
            </div>
          </div>
        </div>
        @endif
      </div>
    </div>
  </div>
</div>
@if(Session::has('status') and Session::has('message') )
@if(Session::has('status') == 'success')
<script>
$(document).ready( function() {
  var url = window.location.href;
var tempurl = url.split('dashboard')[0];
iosOverlay({
    text: "{{Session::get('message')}}",
    duration: 5e3,
    icon: tempurl+'images/notifications/check.png'
  });
});
</script>
{{Session::forget('status'); Session::forget('message');}}
@elseif(Session::has('status') == 'error')
<script>
$(document).ready( function() {
  var url = window.location.href;
var tempurl = url.split('dashboard')[0];
  iosOverlay({
    text: "{{Session::get('message')}}",
    duration: 5e3,
    icon: tempurl+'images/notifications/cross.png'
  });
});
</script>
{{Session::forget('status'); Session::forget('message');}}
@endif
@endif

<!-- Delete Event Popup -->
<div id="myModal-item-delete" class="modal cal_light_box hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">{{trans('92five.really')}} ?</h3>
  </div>
  <div class="modal-body">
    <div class="confirm-delete">{{trans('92five.confirmDeleteEvent')}}?</div>
    <div class="confirm-button">
      <form method="post" action="{{url('dashboard/calendar/event/delete')}}">  <input type="hidden" name="deleteEventId" id="deleteEventId" value=  > <button class="submit">{{trans('92five.yesPlease')}}.</a></button></form>
    <button class="submit dontdelete" id="dontdelete" >{{trans('92five.noThanks')}}.</a></button></div>
  </div>
</div>
<!-- End Delete Event Popup-->
@stop
@section('endjs')
<script>
 $(document).on("click", ".delevent", function() {
   var entityid = $(this).attr('eventid');
   $('#deleteEventId').val(entityid);
   $('#myModal-item-delete').modal('show');
 });
 $(document).on("click", ".dontdelete", function() {
   $('#myModal-item-delete').modal('hide');
 });
</script>
  @stop